packages:
  - .

ignoredBuiltDependencies:
  - '@prisma/engines'
  - prisma
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - '@prisma/client'

peerDependencyRules:
    allowAny:
        - '@hono/zod-validator'
        - 'zod'
        - 'zod-openapi'